name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # or whatever Node version you need

      - name: Install dependencies
        run: npm install

      - name: Build and deploy website
        run: npm run build:deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
